name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    name: Node unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '21']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 7.19.0
          run_install: true

      - name: Lint source
        run: |
          pnpm check:ci

      - name: Build package
        run: |
          pnpm build

      - name: Run tests
        run: |
          pnpm test
        env:
          CI: true

      - name: 'Consume changesets'
        if: github.event_name == 'push' && github.repository == 'ivandotv/puntoenv' && matrix.node == 21 && github.ref == 'refs/heads/main'
        uses: changesets/action@v1
        id: 'changesets'
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          commit: version bump
          title: Next release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
